# Generated by Django 3.0.6 on 2020-05-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epoka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas', models.TextField(blank=True, null=True)),
                ('sredniWynik', models.TextField(blank=True, default='Brak danych')),
                ('odchylenieStandardowe', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True)),
                ('iteracja', models.TextField(blank=True, default='Brak danych')),
            ],
        ),
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakres1', models.FloatField()),
                ('zakres2', models.FloatField()),
                ('wielkoscPopulacji', models.IntegerField()),
                ('liczbaepok', models.IntegerField()),
                ('metodaSelekcji', models.TextField()),
                ('implementacjaKrzyzowania', models.TextField()),
                ('prawdobodobienstwoKrzyzowania', models.IntegerField()),
                ('implementacjaMutowania', models.TextField()),
                ('prawdobodobienstwoMutowania', models.IntegerField()),
                ('ileprzechodzi', models.IntegerField()),
                ('rodzaj_Optymalizacj', models.TextField()),
                ('wielkosc_turnieju', models.IntegerField(blank=True)),
                ('elita', models.IntegerField(blank=True)),
                ('zakresMutacji1', models.FloatField(blank=True)),
                ('zakresMutacji2', models.FloatField(blank=True)),
                ('ID_Wyniku', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wynik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PojedynczaWartoscWyniku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.FloatField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('Wynik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Epoka')),
            ],
        ),
        migrations.AddField(
            model_name='epoka',
            name='rezultaty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Wynik'),
        ),
        migrations.AddField(
            model_name='epoka',
            name='ustawienia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Ustawienia'),
        ),
    ]
